import RPi.GPIO as gpio
import time
  # Declarando cada Led
led_1 = 2
led_2 = 3
led_3 = 4
led_4 = 17
led_5 = 27
led_6 = 22
led_7 = 10
led_8 = 9
led_9 = 11
  # Set output para cada Led
gpio.setmode(gpio.BCM)
gpio.setup(2, gpio.OUT)
gpio.setup(3, gpio.OUT)
gpio.setup(4, gpio.OUT)
gpio.setup(17, gpio.OUT)
gpio.setup(27, gpio.OUT)
gpio.setup(22, gpio.OUT)
gpio.setup(10, gpio.OUT)
gpio.setup(9, gpio.OUT)
gpio.setup(11, gpio.OUT)
  # Set botões 1 e 2
gpio.setup(14, gpio.IN, pull_up_down=gpio.PUD_DOWN)
gpio.setup(15, gpio.IN, pull_up_down=gpio.PUD_DOWN)
  # Sequências
def sequence2(): # Definindo a sequência 2
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    time.sleep(1)
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    time.sleep(1)
def sequence3(): # Definindo a sequência 3
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
def sequence4(): # Definindo a sequência 4
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(22,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(22,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(4,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(17,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    time.sleep(1)
def sequence6(): # Definindo a sequência 6
    gpio.output(2,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(4,gpio.LOW)
    gpio.output(10,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(27,gpio.HIGH)
    gpio.output(2,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(27,gpio.LOW)
    gpio.output(2,gpio.LOW)
    gpio.output(4,gpio.LOW)
    gpio.output(10,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(27,gpio.HIGH)
    time.sleep(1)
    gpio.output(27,gpio.LOW)
    time.sleep(1)
def sequence7(): # Definindo a sequência 7
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(10,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(2,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(11,gpio.LOW)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(4,gpio.LOW)
    time.sleep(1)
def sequence8(): # Definindo a sequência 8
    gpio.output(10,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    time.sleep(1)
def sequence10(): # Definindo a sequência 10
    gpio.output(2,gpio.HIGH)
    gpio.output(3,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(17,gpio.LOW)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
    gpio.output(22,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
def sequence11(): # Definindo a sequência 11
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(2,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(11,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
def sequence12(): # Definindo a sequência 12
    gpio.output(10,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    time.sleep(1)
    gpio.output(22,gpio.LOW)
    gpio.output(3,gpio.LOW)
    time.sleep(1)
    gpio.output(11,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(2,gpio.LOW)
    time.sleep(1)
    gpio.output(9,gpio.LOW)
    gpio.output(17,gpio.LOW)
    time.sleep(1)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
def sequence14(): # Definindo a sequência 14
    gpio.output(10,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(22,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(17,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    time.sleep(1)
def sequence15(): # Definindo a sequência 15
    gpio.output(2,gpio.HIGH)
    gpio.output(3,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    time.sleep(1)
    gpio.output(11,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(10,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    time.sleep(1)
    gpio.output(27,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(3,gpio.LOW)
    gpio.output(4,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(11,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(10,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(27,gpio.LOW)
    time.sleep(1)
def sequence18(): # Definindo a sequência 18
    gpio.output(4,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
def sequence19(): # Definindo a sequência 19
    gpio.output(27,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(4,gpio.LOW)
    gpio.output(10,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(4,gpio.LOW)
    gpio.output(10,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(27,gpio.LOW)
    time.sleep(1)
def sequence20(): # Definindo a sequência 20
    gpio.output(10,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(27,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(4,gpio.LOW)
    gpio.output(10,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(2,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(4,gpio.LOW)
    gpio.output(10,gpio.LOW)
    gpio.output(11,gpio.LOW)
    gpio.output(3,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(10,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(2,gpio.LOW)
    gpio.output(11,gpio.LOW)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(4,gpio.LOW)
    time.sleep(1)
def sequence22(): # Definindo a sequência 22
    gpio.output(10,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    time.sleep(1)
    gpio.output(27,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(22,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(4,gpio.LOW)
    gpio.output(11,gpio.LOW)
    gpio.output(10,gpio.LOW)
    gpio.output(3,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(2,gpio.HIGH)
    gpio.output(4,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    time.sleep(1)
    gpio.output(10,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    gpio.output(2,gpio.LOW)
    gpio.output(11,gpio.LOW)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(4,gpio.LOW)
    time.sleep(1)
def sequence23(): # Definindo a sequência 23
    gpio.output(2,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
def sequence24(): # Definindo a sequência 24
    gpio.output(4,gpio.HIGH)
    gpio.output(27,gpio.HIGH)
    gpio.output(10,gpio.HIGH)
    time.sleep(1)
    gpio.output(3,gpio.HIGH)
    gpio.output(22,gpio.HIGH)
    gpio.output(17,gpio.HIGH)
    gpio.output(9,gpio.HIGH)
    time.sleep(1)
    gpio.output(2,gpio.HIGH)
    gpio.output(11,gpio.HIGH)
    time.sleep(1)
    gpio.output(4,gpio.LOW)
    gpio.output(27,gpio.LOW)
    gpio.output(10,gpio.LOW)
    time.sleep(1)
    gpio.output(3,gpio.LOW)
    gpio.output(22,gpio.LOW)
    gpio.output(17,gpio.LOW)
    gpio.output(9,gpio.LOW)
    time.sleep(1)
    gpio.output(2,gpio.LOW)
    gpio.output(11,gpio.LOW)
    time.sleep(1)
  # Comando dos Botões
while True:
    if gpio.input(14) == True and gpio.input(15) == False: # Apenas o botão 1
        while gpio.input(15) == False and gpio.input(14) == True:
            # Primeira Combinação --> 4, 8, 12, 20, 24
            sequence4(); sequence8(); sequence12(); sequence20(); sequence24()
        
    if gpio.input(15) == True and gpio.input(14) == False: # Apenas o botão 2
        while gpio.input(15) == True and gpio.input(14) == False:
            # Segunda Combinação --> 2, 6, 10, 14, 18, 22
            sequence2(); sequence6(); sequence10(); sequence14(); sequence18(); sequence22()
        
    if gpio.input(14) == True and gpio.input(15) == True: # Ambos os botões 1 e 2
        while gpio.input(15) == True and gpio.input(14) == True:
            # Terceira Combinação --> 3, 7, 11, 15, 19, 23
            sequence3(); sequence7(); sequence11(); sequence15(); sequence19(); sequence23()
